input_obs_shape (1000, 11, 11, 14)
/root/miniconda3/envs/jax/lib/python3.10/site-packages/jax/_src/ops/scatter.py:96: FutureWarning: scatter inputs have incompatible types: cannot safely cast value from dtype=int32 to dtype=int16 with jax_numpy_dtype_promotion='standard'. In future JAX releases this will result in an error.
  warnings.warn(
Error executing job with overrides: []
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/autodl-tmp/SocialJaxProject/algothrims/IPPO/ippo_cnn_coins.py", line 564, in main
    single_run(config)
  File "/root/autodl-tmp/SocialJaxProject/algothrims/IPPO/ippo_cnn_coins.py", line 420, in single_run
    out = jax.vmap(train_jit)(rngs)
  File "/root/autodl-tmp/SocialJaxProject/algothrims/IPPO/ippo_cnn_coins.py", line 396, in train
    runner_state, metric = jax.lax.scan(
  File "/root/autodl-tmp/SocialJaxProject/algothrims/IPPO/ippo_cnn_coins.py", line 263, in _update_step
    runner_state, traj_batch = jax.lax.scan(
  File "/root/autodl-tmp/SocialJaxProject/algothrims/IPPO/ippo_cnn_coins.py", line 242, in _env_step
    obsv, env_state, reward, done, info = jax.vmap(
  File "/root/autodl-tmp/SocialJaxProject/socialjax/wrappers/baselines.py", line 86, in step
    new_episode_return = state.episode_returns + self._batchify_floats(reward)
  File "/root/autodl-tmp/SocialJaxProject/socialjax/wrappers/baselines.py", line 42, in _batchify_floats
    return jnp.stack([x[a] for a in self._env.agents])
  File "/root/autodl-tmp/SocialJaxProject/socialjax/wrappers/baselines.py", line 42, in <listcomp>
    return jnp.stack([x[a] for a in self._env.agents])
  File "/root/miniconda3/envs/jax/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 743, in op
    return getattr(self.aval, f"_{name}")(self, *args)
  File "/root/miniconda3/envs/jax/lib/python3.10/site-packages/jax/_src/numpy/array_methods.py", line 356, in _getitem
    return lax_numpy._rewriting_take(self, item)
  File "/root/miniconda3/envs/jax/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4494, in _rewriting_take
    return _gather(arr, treedef, static_idx, dynamic_idx, indices_are_sorted,
  File "/root/miniconda3/envs/jax/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4503, in _gather
    indexer = _index_to_gather(shape(arr), idx)  # shared with _scatter_update
  File "/root/miniconda3/envs/jax/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4604, in _index_to_gather
    idx = _canonicalize_tuple_index(len(x_shape), idx)
  File "/root/miniconda3/envs/jax/lib/python3.10/site-packages/jax/_src/numpy/lax_numpy.py", line 4913, in _canonicalize_tuple_index
    raise IndexError(
IndexError: Too many indices for array: 1 non-None/Ellipsis indices for dim 0.

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.
